//! Unicode CLDR's sentence-break suppressions as `.desm` files.
//!
//! [`convert`] turns one `common/segments/<tag>.xml` into a `.desm`
//! text (or nothing, when the file tailors no sentence breaks). With
//! the `fetch` feature, [`fetch`] takes a whole release from the
//! CLDR repository at its release tag — immutable, so a fetch by
//! version is reproducible — and [`latest`] asks which release that
//! is today. The crate's own `cldr/` directory is written by the
//! same code (`desm cldr get <version> --into cldr/`).

/// The `.desm` text for one CLDR segments file, `None` when it
/// carries no sentence-break suppressions (many tailor only line or
/// word breaks).
pub fn convert(xml: &str, tag: &str, version: &str) -> Option<String> {
    let block = regex::Regex::new(r#"(?s)<segmentation type="SentenceBreak">(.*?)</segmentation>"#)
        .expect("static regex")
        .captures(xml)?;
    let item = regex::Regex::new(r"<suppression>([^<]*)</suppression>").expect("static regex");
    let mut list: Vec<String> = item
        .captures_iter(&block[1])
        .map(|c| c[1].trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    if list.is_empty() {
        return None;
    }
    list.sort_by_key(|s| (s.to_lowercase(), s.clone()));
    list.dedup();
    let mut out = format!(
        "# {tag}.desm — sentence bonds: Unicode CLDR {version}, {tag}\n\
         #\n\
         # Unicode CLDR's sentence-break suppressions for `{tag}`, verbatim:\n\
         # release {version} (git tag release-{git}), common/segments/{tag}.xml,\n\
         # <suppressions type=\"standard\">. © Unicode, Inc.; Unicode License\n\
         # (LICENSE-UNICODE). A bare line is an abbreviation a sentence may\n\
         # end in without ending. Generated by `desm cldr get {version}`;\n\
         # regenerate from a release rather than editing, and put local\n\
         # additions in your own .desm that `#!include`s this one.\n\n",
        git = version.replace('.', "-")
    );
    for s in list {
        out.push_str(&s);
        out.push('\n');
    }
    Some(out)
}

/// The version string of a CLDR git tag: `release-48-2` → `48.2`,
/// `release-47` → `47`.
pub fn version_of_tag(tag: &str) -> Option<String> {
    let rest = tag.strip_prefix("release-")?;
    let parts: Vec<&str> = rest.split('-').collect();
    if parts.is_empty()
        || parts
            .iter()
            .any(|p| p.is_empty() || !p.chars().all(|c| c.is_ascii_digit()))
    {
        return None;
    }
    Some(parts.join("."))
}

#[cfg(feature = "fetch")]
fn get(url: &str) -> Result<String, String> {
    let mut resp = ureq::get(url)
        .header(
            "User-Agent",
            concat!("syndesmos/", env!("CARGO_PKG_VERSION")),
        )
        .call()
        .map_err(|e| format!("{url}: {e}"))?;
    resp.body_mut()
        .read_to_string()
        .map_err(|e| format!("{url}: {e}"))
}

/// The latest CLDR release's version (`"48.2"`), from the
/// repository's tags.
#[cfg(feature = "fetch")]
pub fn latest() -> Result<String, String> {
    let json = get("https://api.github.com/repos/unicode-org/cldr/tags?per_page=100")?;
    let name = regex::Regex::new(r#""name"\s*:\s*"(release-[0-9-]+)""#).expect("static regex");
    let mut best: Option<(Vec<u32>, String)> = None;
    for c in name.captures_iter(&json) {
        if let Some(v) = version_of_tag(&c[1]) {
            let key: Vec<u32> = v.split('.').map(|p| p.parse().unwrap_or(0)).collect();
            if best.as_ref().is_none_or(|(k, _)| key > *k) {
                best = Some((key, v));
            }
        }
    }
    best.map(|(_, v)| v)
        .ok_or_else(|| "no release tag found in the CLDR repository's tags".to_string())
}

/// Every language of a CLDR release that carries sentence-break
/// suppressions, as `(tag, .desm text)`; `version` is `"48.2"`-shaped
/// or `"latest"`.
#[cfg(feature = "fetch")]
pub fn fetch(version: &str) -> Result<(String, Vec<(String, String)>), String> {
    let version = if version == "latest" {
        latest()?
    } else {
        version.to_string()
    };
    let tag = format!("release-{}", version.replace('.', "-"));
    let listing = get(&format!(
        "https://api.github.com/repos/unicode-org/cldr/contents/common/segments?ref={tag}"
    ))?;
    let name = regex::Regex::new(r#""name"\s*:\s*"([A-Za-z_]+)\.xml""#).expect("static regex");
    let mut out = Vec::new();
    for c in name.captures_iter(&listing) {
        let lang = &c[1];
        let xml = get(&format!(
            "https://raw.githubusercontent.com/unicode-org/cldr/{tag}/common/segments/{lang}.xml"
        ))?;
        if let Some(text) = convert(&xml, lang, &version) {
            out.push((lang.to_string(), text));
        }
    }
    if out.is_empty() {
        return Err(format!(
            "CLDR {version}: no sentence-break suppressions found (is the release tag right?)"
        ));
    }
    out.sort();
    Ok((version, out))
}

/// The per-user cache directory for fetched releases:
/// `$XDG_CACHE_HOME/syndesmos/cldr` (else `~/.cache/syndesmos/cldr`).
pub fn cache_dir() -> Option<std::path::PathBuf> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".cache")))?;
    Some(base.join("syndesmos").join("cldr"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converts_sentence_suppressions_only() {
        let xml = r#"<ldml><segmentations>
<segmentation type="LineBreak"><suppressions type="standard"><suppression>x.</suppression></suppressions></segmentation>
<segmentation type="SentenceBreak"><suppressions type="standard">
<suppression>Mr.</suppression><suppression> Dr. </suppression><suppression>Mr.</suppression>
</suppressions></segmentation></segmentations></ldml>"#;
        let d = convert(xml, "xx", "48.2").unwrap();
        assert!(d.starts_with("# xx.desm — sentence bonds: Unicode CLDR 48.2, xx\n"));
        assert!(d.contains("release-48-2"));
        assert!(d.ends_with("\nDr.\nMr.\n"), "{d}");
        assert!(convert("<ldml/>", "xx", "48.2").is_none());
        assert_eq!(version_of_tag("release-48-2").as_deref(), Some("48.2"));
        assert_eq!(version_of_tag("release-47").as_deref(), Some("47"));
        assert!(version_of_tag("release-48-alpha1").is_none());
    }
}
