//! Unicode CLDR's sentence-break suppressions as `.desm` files.
//!
//! [`convert`] turns one `common/segments/<tag>.xml` into a `.desm`
//! text (or nothing, when the file tailors no sentence breaks). With
//! the `fetch` feature, [`fetch`] reads a whole release from the
//! archive Unicode publishes at `unicode.org/Public/cldr/<version>/`
//! — a release never changes, so a fetch by version is reproducible
//! — and [`latest`] asks which release is the newest there. The
//! crate's own `cldr/` directory is written by the same code
//! (`desm cldr get <version> --into cldr/`).

/// The `.desm` text for one CLDR segments file, `None` when it
/// carries no sentence-break suppressions (many tailor only line or
/// word breaks).
pub fn convert(xml: &str, tag: &str, version: &str) -> Option<String> {
    let block = regex::Regex::new(r#"(?s)<segmentation type="SentenceBreak">(.*?)</segmentation>"#)
        .expect("static regex")
        .captures(xml)?;
    let item = regex::Regex::new(r"<suppression>([^<]*)</suppression>").expect("static regex");
    let mut list: Vec<String> = item
        .captures_iter(&block[1])
        .map(|c| c[1].trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    if list.is_empty() {
        return None;
    }
    list.sort_by_key(|s| (s.to_lowercase(), s.clone()));
    list.dedup();
    let mut out = format!(
        "# {tag}.desm — sentence bonds: Unicode CLDR {version}, {tag}\n\
         #\n\
         # Unicode CLDR's sentence-break suppressions for `{tag}`, verbatim:\n\
         # release {version} (git tag release-{git}), common/segments/{tag}.xml,\n\
         # <suppressions type=\"standard\">. © Unicode, Inc.; Unicode License\n\
         # (LICENSE-UNICODE). A bare line is an abbreviation a sentence may\n\
         # end in without ending. Generated by `desm cldr get {version}`;\n\
         # regenerate from a release rather than editing, and put local\n\
         # additions in your own .desm that `#!include`s this one.\n\n",
        git = version.replace('.', "-")
    );
    for s in list {
        out.push_str(&s);
        out.push('\n');
    }
    Some(out)
}

/// The version string of a CLDR git tag: `release-48-2` → `48.2`,
/// `release-47` → `47`.
pub fn version_of_tag(tag: &str) -> Option<String> {
    let rest = tag.strip_prefix("release-")?;
    let parts: Vec<&str> = rest.split('-').collect();
    if parts.is_empty()
        || parts
            .iter()
            .any(|p| p.is_empty() || !p.chars().all(|c| c.is_ascii_digit()))
    {
        return None;
    }
    Some(parts.join("."))
}

#[cfg(feature = "fetch")]
fn agent() -> ureq::Agent {
    ureq::Agent::new_with_defaults()
}

#[cfg(feature = "fetch")]
fn get_text(url: &str) -> Result<String, String> {
    agent()
        .get(url)
        .header(
            "User-Agent",
            concat!("syndesmos/", env!("CARGO_PKG_VERSION")),
        )
        .call()
        .map_err(|e| format!("{url}: {e}"))?
        .body_mut()
        .read_to_string()
        .map_err(|e| format!("{url}: {e}"))
}

#[cfg(feature = "fetch")]
fn get_bytes(url: &str) -> Result<Vec<u8>, String> {
    agent()
        .get(url)
        .header(
            "User-Agent",
            concat!("syndesmos/", env!("CARGO_PKG_VERSION")),
        )
        .call()
        .map_err(|e| format!("{url}: {e}"))?
        .body_mut()
        .with_config()
        .limit(256 * 1024 * 1024)
        .read_to_vec()
        .map_err(|e| format!("{url}: {e}"))
}

/// Where Unicode publishes the releases.
const PUBLIC: &str = "https://unicode.org/Public/cldr";

/// The URL of a release's `cldr-common-<version>.zip`, the archive
/// that holds `common/segments/`.
pub fn archive_url(version: &str) -> String {
    format!("{PUBLIC}/{version}/cldr-common-{version}.zip")
}

/// The version directories an index page of `unicode.org/Public/cldr/`
/// lists, highest first (`48.2` above `48`).
pub fn versions_in_index(html: &str) -> Vec<String> {
    let dir = regex::Regex::new(r#"href="([0-9]+(?:\.[0-9]+)*)/""#).expect("static regex");
    let mut out: Vec<String> = dir.captures_iter(html).map(|c| c[1].to_string()).collect();
    out.sort_by_key(|v| std::cmp::Reverse(version_key(v)));
    out.dedup();
    out
}

fn version_key(v: &str) -> Vec<u32> {
    v.split('.').map(|p| p.parse().unwrap_or(0)).collect()
}

/// The latest CLDR release's version (`"48.2"`): the highest
/// version directory on unicode.org that holds a release archive.
/// A directory prepared for a coming release has none yet and is
/// passed over.
#[cfg(feature = "fetch")]
pub fn latest() -> Result<String, String> {
    let index = get_text(&format!("{PUBLIC}/"))?;
    for v in versions_in_index(&index) {
        let ok = agent()
            .head(&archive_url(&v))
            .header(
                "User-Agent",
                concat!("syndesmos/", env!("CARGO_PKG_VERSION")),
            )
            .call()
            .map(|r| r.status().is_success())
            .unwrap_or(false);
        if ok {
            return Ok(v);
        }
    }
    Err(format!("no release archive found under {PUBLIC}/"))
}

/// Every language of a CLDR release that carries sentence-break
/// suppressions, as `(tag, .desm text)`, read from the release
/// archive on unicode.org; `version` is `"48.2"`-shaped or
/// `"latest"`. The archive is a few tens of megabytes: a fetch is a
/// maintenance step, not a build step.
#[cfg(feature = "fetch")]
pub fn fetch(version: &str) -> Result<(String, Vec<(String, String)>), String> {
    let version = if version == "latest" {
        latest()?
    } else {
        version.to_string()
    };
    let url = archive_url(&version);
    let bytes = get_bytes(&url)?;
    let mut zip =
        zip::ZipArchive::new(std::io::Cursor::new(bytes)).map_err(|e| format!("{url}: {e}"))?;
    let mut out = Vec::new();
    for i in 0..zip.len() {
        let mut entry = zip.by_index(i).map_err(|e| format!("{url}: {e}"))?;
        let name = entry.name().to_string();
        let Some(file) = name.strip_prefix("common/segments/") else {
            continue;
        };
        let Some(lang) = file.strip_suffix(".xml") else {
            continue;
        };
        let mut xml = String::new();
        std::io::Read::read_to_string(&mut entry, &mut xml)
            .map_err(|e| format!("{url}: {name}: {e}"))?;
        if let Some(text) = convert(&xml, lang, &version) {
            out.push((lang.to_string(), text));
        }
    }
    if out.is_empty() {
        return Err(format!(
            "CLDR {version}: no sentence-break suppressions in {url}"
        ));
    }
    out.sort();
    Ok((version, out))
}

/// The per-user cache directory for fetched releases:
/// `$XDG_CACHE_HOME/syndesmos/cldr` (else `~/.cache/syndesmos/cldr`).
pub fn cache_dir() -> Option<std::path::PathBuf> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".cache")))?;
    Some(base.join("syndesmos").join("cldr"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converts_sentence_suppressions_only() {
        let xml = r#"<ldml><segmentations>
<segmentation type="LineBreak"><suppressions type="standard"><suppression>x.</suppression></suppressions></segmentation>
<segmentation type="SentenceBreak"><suppressions type="standard">
<suppression>Mr.</suppression><suppression> Dr. </suppression><suppression>Mr.</suppression>
</suppressions></segmentation></segmentations></ldml>"#;
        let d = convert(xml, "xx", "48.2").unwrap();
        assert!(d.starts_with("# xx.desm — sentence bonds: Unicode CLDR 48.2, xx\n"));
        assert!(d.contains("release-48-2"));
        assert!(d.ends_with("\nDr.\nMr.\n"), "{d}");
        assert!(convert("<ldml/>", "xx", "48.2").is_none());
        assert_eq!(version_of_tag("release-48-2").as_deref(), Some("48.2"));
        assert_eq!(version_of_tag("release-47").as_deref(), Some("47"));
        assert!(version_of_tag("release-48-alpha1").is_none());
        let index = r#"<a href="47/">47/</a> <a href="48/">48/</a> <a href="48.2/">48.2/</a> <a href="49/">49/</a> <a href="48.1/">48.1/</a> <a href="?C=N;O=D">Name</a>"#;
        assert_eq!(versions_in_index(index), ["49", "48.2", "48.1", "48", "47"]);
        assert_eq!(
            archive_url("48.2"),
            "https://unicode.org/Public/cldr/48.2/cldr-common-48.2.zip"
        );
    }
}
