//! # syndesmos — sentence bonds over UAX #29
//!
//! Unicode's sentence rules (UAX #29) know nothing of a language's
//! abbreviations, so they break after *Dr.* and before *Smith*. A
//! `.desm` file names the bonds: the places where a sentence runs on
//! across a break the rules made. Atoms stay what the rules cut;
//! the bonds say which of them read as one sentence — molecules
//! from atoms.
//!
//! The core is an overlay: [`Syndesmos::apply`] takes a text and the
//! boundaries some UAX #29 implementation produced and returns the
//! ones that survive the bonds. That contract is the standard, and
//! it is what CLDR's sentence-break suppressions already mean.
//! With the `uax29` feature (default) the crate also offers the
//! drop-in — [`Syndesmos::unicode_sentences`] and
//! [`Syndesmos::split_sentence_bound_indices`], the same names as
//! unicode-segmentation's, bonds applied.
//!
//! The crate ships Unicode CLDR's sentence-break suppressions per
//! language under `cldr/`, release [`CLDR_VERSION`], generated by
//! its own [`cldr`] module; a file reaches them with `#!cldr en`,
//! code with [`Syndesmos::cldr`], and `desm cldr get <version>`
//! fetches any release as `.desm` files.
//!
//! ## The `.desm` file
//!
//! One rule per line; `#` comments and blank lines are ignored.
//!
//! - A **bare line** is an abbreviation, a whole word a sentence may
//!   end in without ending: `Dr.`, `Mrs.`, `e.g.`. The break after
//!   it is undone. What precedes the word must be the start, a
//!   space, or another non-letter, so `Undr.` is not `Dr.`.
//! - A **`/regex/` line** undoes a break that a match *straddles*:
//!   the match begins before the boundary and reaches it. UAX #29
//!   places the boundary at the start of the next segment, after
//!   the whitespace, so a pattern that spans the space spans the
//!   break: `/[A-Z]\. [A-Z]/` keeps initials together,
//!   `/[?!]” [a-z]/` keeps *“Why?” he asked* one sentence. `\/`
//!   escapes a slash; a trailing `i` folds case.
//! - `#!cldr TAG [VERSION]` merges CLDR's suppressions for a
//!   language: the release this crate ships when no version is
//!   written or it matches, else a release fetched into the cache
//!   by `desm cldr get VERSION`. `#!include PATH` merges another
//!   `.desm`, resolved against the including file's directory. The
//!   `#!` prefix is a comment to any reader that knows no
//!   directives, and a bond line never begins with `#`.
//!
//! The regex flavor is the `regex` crate's: Unicode classes and
//! properties, no lookaround, no backreferences, linear-time. Every
//! rule of a file compiles into one set, and each boundary is tested
//! in one pass over a bounded window around it.

pub mod cldr;

use regex::{Regex, RegexBuilder, RegexSet, RegexSetBuilder};
use std::fmt;

/// How far, in bytes, a pattern may reach on either side of a
/// boundary. A rule longer than this is not a sentence bond.
const WINDOW: usize = 96;

/// A failure to read a `.desm` file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseError {
    /// 1-based line in the file.
    pub line: usize,
    pub message: String,
}

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "line {}: {}", self.line, self.message)
    }
}

impl std::error::Error for ParseError {}

/// The Unicode CLDR release the shipped lists come from.
pub const CLDR_VERSION: &str = "48.2";

/// CLDR's sentence-break suppressions per language tag, verbatim
/// from release [`CLDR_VERSION`] (`common/segments/<tag>.xml`),
/// written by `desm cldr get 48.2 --into cldr/`.
const CLDR: &[(&str, &str)] = &[
    ("de", include_str!("../cldr/de.desm")),
    ("en", include_str!("../cldr/en.desm")),
    ("es", include_str!("../cldr/es.desm")),
    ("fr", include_str!("../cldr/fr.desm")),
    ("it", include_str!("../cldr/it.desm")),
    ("pt", include_str!("../cldr/pt.desm")),
    ("ru", include_str!("../cldr/ru.desm")),
];

/// A set of sentence bonds: the rules of one or more `.desm` files.
#[derive(Debug, Clone, Default)]
pub struct Syndesmos {
    abbreviations: Vec<String>,
    /// Each pattern's source spelling (as written, with flags) and
    /// its compiled form.
    patterns: Vec<(String, Regex)>,
    /// The patterns as one set, rebuilt when they change.
    set: Option<RegexSet>,
}

impl Syndesmos {
    /// No bonds: every UAX #29 boundary stands.
    pub fn empty() -> Self {
        Self::default()
    }

    /// The language tags the crate ships CLDR's suppressions for.
    pub fn cldr_languages() -> Vec<&'static str> {
        CLDR.iter().map(|(t, _)| *t).collect()
    }

    /// CLDR's sentence-break suppressions for a language tag
    /// (`"en"`), release [`CLDR_VERSION`] — what `#!cldr en` merges.
    pub fn cldr(tag: &str) -> Option<Self> {
        let (_, text) = CLDR.iter().find(|(t, _)| *t == tag)?;
        Some(Self::parse(text).expect("the CLDR files parse"))
    }

    /// CLDR's suppressions for a tag at a release: the shipped one
    /// when `version` is `None` or [`CLDR_VERSION`], else the copy
    /// `desm cldr get VERSION` left in the cache.
    fn cldr_at(tag: &str, version: Option<&str>) -> Result<Self, String> {
        match version {
            None => Self::cldr(tag).ok_or_else(|| {
                format!(
                    "no CLDR list for {tag:?} (CLDR {CLDR_VERSION} has: {})",
                    Self::cldr_languages().join(", ")
                )
            }),
            Some(v) if v == CLDR_VERSION => Self::cldr_at(tag, None),
            Some(v) => {
                let path = cldr::cache_dir()
                    .ok_or_else(|| "no cache directory (set HOME or XDG_CACHE_HOME)".to_string())?
                    .join(v)
                    .join(format!("{tag}.desm"));
                let text = std::fs::read_to_string(&path).map_err(|_| {
                    format!(
                        "CLDR {v} is not the release this syndesmos ships ({CLDR_VERSION}) and is not in the cache ({}); run `desm cldr get {v}`",
                        path.display()
                    )
                })?;
                Self::parse(&text).map_err(|e| format!("{}: {e}", path.display()))
            }
        }
    }

    /// Read a `.desm` text. A `#!include` line needs a file to
    /// resolve against; use [`load`](Self::load) for that.
    pub fn parse(text: &str) -> Result<Self, ParseError> {
        Self::parse_in(text, None, &mut Vec::new())
    }

    fn parse_in(
        text: &str,
        base: Option<&std::path::Path>,
        stack: &mut Vec<std::path::PathBuf>,
    ) -> Result<Self, ParseError> {
        let mut out = Self::empty();
        for (i, raw) in text.lines().enumerate() {
            let line = i + 1;
            let l = raw.trim();
            if l.is_empty() {
                continue;
            }
            if let Some(directive) = l.strip_prefix("#!") {
                let directive = directive.trim();
                if let Some(args) = directive.strip_prefix("cldr ") {
                    let mut it = args.split_whitespace();
                    let tag = it.next().unwrap_or("");
                    let version = it.next();
                    if tag.is_empty() || it.next().is_some() {
                        return Err(ParseError {
                            line,
                            message: "#!cldr takes a language tag and an optional release: #!cldr en 48.2".into(),
                        });
                    }
                    let list = Self::cldr_at(tag, version)
                        .map_err(|message| ParseError { line, message })?;
                    out.extend(list);
                    continue;
                }
                let Some(rel) = directive.strip_prefix("include ") else {
                    return Err(ParseError {
                        line,
                        message: format!(
                            "unknown directive #!{directive} (have: #!cldr TAG [VERSION], #!include PATH)"
                        ),
                    });
                };
                let rel = rel.trim();
                let Some(base) = base else {
                    return Err(ParseError {
                        line,
                        message:
                            "#!include needs a file to resolve against; load the .desm from a path"
                                .into(),
                    });
                };
                let path = base.join(rel);
                let canon = std::fs::canonicalize(&path).map_err(|e| ParseError {
                    line,
                    message: format!("#!include {rel}: {e}"),
                })?;
                if stack.contains(&canon) {
                    return Err(ParseError {
                        line,
                        message: format!(
                            "#!include {rel}: include cycle through {}",
                            canon.display()
                        ),
                    });
                }
                let included = std::fs::read_to_string(&canon).map_err(|e| ParseError {
                    line,
                    message: format!("#!include {rel}: {e}"),
                })?;
                stack.push(canon.clone());
                let inner =
                    Self::parse_in(&included, canon.parent(), stack).map_err(|e| ParseError {
                        line,
                        message: format!("#!include {rel}: {e}"),
                    })?;
                stack.pop();
                out.extend(inner);
                continue;
            }
            if l.starts_with('#') {
                continue;
            }
            if let Some(rest) = l.strip_prefix('/') {
                let (pattern, tail) = split_pattern(rest).ok_or_else(|| ParseError {
                    line,
                    message: "unclosed /regex/".into(),
                })?;
                let mut flags = String::new();
                let mut tail = tail;
                while let Some(c) = tail.chars().next() {
                    if c == 'i' {
                        flags.push(c);
                        tail = &tail[1..];
                    } else {
                        break;
                    }
                }
                let tail = tail.trim();
                if !tail.is_empty() && !tail.starts_with('#') {
                    return Err(ParseError {
                        line,
                        message: format!(
                            "after the /regex/ only the flag `i` or a # comment may follow, not {tail:?}"
                        ),
                    });
                }
                let re = RegexBuilder::new(&pattern)
                    .case_insensitive(flags.contains('i'))
                    .build()
                    .map_err(|e| ParseError {
                        line,
                        message: format!("bad regex: {e}"),
                    })?;
                let source = format!("/{pattern}/{flags}");
                out.patterns.push((source, re));
                continue;
            }
            // A bare abbreviation, comment allowed after two spaces.
            let word = match l.find("  #") {
                Some(at) => l[..at].trim_end(),
                None => l,
            };
            out.abbreviations.push(word.to_string());
        }
        out.rebuild();
        Ok(out)
    }

    /// Read a `.desm` file; `#!include` lines resolve against its
    /// directory.
    pub fn load(path: impl AsRef<std::path::Path>) -> Result<Self, Box<dyn std::error::Error>> {
        let path = path.as_ref();
        let text = std::fs::read_to_string(path)?;
        let canon = std::fs::canonicalize(path)?;
        let mut stack = vec![canon.clone()];
        Ok(Self::parse_in(&text, canon.parent(), &mut stack)?)
    }

    /// Add another set's bonds to this one.
    pub fn extend(&mut self, other: Syndesmos) {
        for a in other.abbreviations {
            if !self.abbreviations.contains(&a) {
                self.abbreviations.push(a);
            }
        }
        for (src, re) in other.patterns {
            if !self.patterns.iter().any(|(s, _)| *s == src) {
                self.patterns.push((src, re));
            }
        }
        self.rebuild();
    }

    fn rebuild(&mut self) {
        self.set = if self.patterns.is_empty() {
            None
        } else {
            Some(
                RegexSetBuilder::new(self.patterns.iter().map(|(s, _)| {
                    // The set needs the flag inside the pattern.
                    let (pat, flags) = s[1..].rsplit_once('/').expect("source has slashes");
                    if flags.contains('i') {
                        format!("(?i){pat}")
                    } else {
                        pat.to_string()
                    }
                }))
                .build()
                .expect("patterns compiled individually"),
            )
        };
    }

    pub fn is_empty(&self) -> bool {
        self.abbreviations.is_empty() && self.patterns.is_empty()
    }

    /// The abbreviations, as written.
    pub fn abbreviations(&self) -> &[String] {
        &self.abbreviations
    }

    /// The patterns, as written (`/…/` with flags).
    pub fn patterns(&self) -> impl Iterator<Item = &str> {
        self.patterns.iter().map(|(s, _)| s.as_str())
    }

    /// Whether a bond undoes the boundary at `at` — the byte offset
    /// where the next segment begins.
    pub fn bonds(&self, text: &str, at: usize) -> bool {
        if at == 0 || at >= text.len() || !text.is_char_boundary(at) {
            return false;
        }
        // The abbreviation rule: the segment before ends in one, as
        // a whole word.
        let before = text[..at].trim_end();
        for a in &self.abbreviations {
            if let Some(head) = before.strip_suffix(a.as_str())
                && head
                    .chars()
                    .next_back()
                    .is_none_or(|c| !c.is_alphanumeric())
            {
                return true;
            }
        }
        // The pattern rule: a match straddles the boundary.
        let Some(set) = &self.set else {
            return false;
        };
        let mut lo = at.saturating_sub(WINDOW);
        while !text.is_char_boundary(lo) {
            lo += 1;
        }
        let mut hi = (at + WINDOW).min(text.len());
        while !text.is_char_boundary(hi) {
            hi -= 1;
        }
        let window = &text[lo..hi];
        let rel = at - lo;
        for idx in set.matches(window) {
            let (_, re) = &self.patterns[idx];
            // Matches may overlap: `/[A-Z]\. [A-Z]/` must straddle
            // both breaks of `J. R. Tolkien`, and the second match
            // begins inside the first. So the search restarts one
            // character after each match's start, not at its end.
            let mut pos = 0;
            while let Some(m) = re.find_at(window, pos) {
                if m.start() >= rel {
                    break;
                }
                if m.end() >= rel {
                    return true;
                }
                pos = m.start() + 1;
                while pos < window.len() && !window.is_char_boundary(pos) {
                    pos += 1;
                }
                if pos > window.len() {
                    break;
                }
            }
        }
        false
    }

    /// The overlay: of the boundaries a UAX #29 implementation
    /// produced (byte offsets where segments begin, the first
    /// segment's 0 excluded), those the bonds leave standing.
    pub fn apply(&self, text: &str, boundaries: &[usize]) -> Vec<usize> {
        boundaries
            .iter()
            .copied()
            .filter(|&b| !self.bonds(text, b))
            .collect()
    }
}

/// The canonical form of a `.desm` text (`desm canon`): the leading
/// comment block verbatim, then the file's `#!cldr` lines with their
/// release made explicit (sorted by tag), then the abbreviations
/// (sorted, case-insensitively then exactly), then the patterns
/// (sorted by source), all deduplicated. `#!include` files are
/// inlined as rules, so the result is self-contained except for the
/// CLDR references, which are versioned by design; comments between
/// and after rules are dropped. `base` resolves includes, as for
/// [`Syndesmos::load`]. `desm hash` is the SHA-256 of this text.
pub fn canon(text: &str, base: Option<&std::path::Path>) -> Result<String, ParseError> {
    let mut head = String::new();
    let mut in_head = true;
    let mut cldr: Vec<(String, String)> = Vec::new();
    let mut rules = Syndesmos::empty();
    let mut stack = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = i + 1;
        let l = raw.trim();
        let is_comment = l.starts_with('#') && !l.starts_with("#!");
        if in_head && (l.is_empty() || is_comment) {
            if !(l.is_empty() && head.is_empty()) {
                head.push_str(raw.trim_end());
                head.push('\n');
            }
            continue;
        }
        in_head = false;
        if l.is_empty() || is_comment {
            continue;
        }
        if let Some(args) = l.strip_prefix("#!cldr ") {
            let mut it = args.split_whitespace();
            let tag = it.next().unwrap_or("").to_string();
            let version = it.next().map(str::to_string);
            if tag.is_empty() || it.next().is_some() {
                return Err(ParseError {
                    line,
                    message: "#!cldr takes a language tag and an optional release: #!cldr en 48.2"
                        .into(),
                });
            }
            // Resolve, so an unknown tag or an unsatisfiable pin is an
            // error here too; then keep the line as a pin.
            Syndesmos::cldr_at(&tag, version.as_deref())
                .map_err(|message| ParseError { line, message })?;
            cldr.push((tag, version.unwrap_or_else(|| CLDR_VERSION.to_string())));
            continue;
        }
        // Everything else parses as one line of a file (includes
        // inlined through the ordinary loader).
        let one = Syndesmos::parse_in(l, base, &mut stack).map_err(|e| ParseError {
            line,
            message: e.message,
        })?;
        rules.extend(one);
    }
    cldr.sort();
    cldr.dedup();
    let mut out = head.trim_end().to_string();
    if !out.is_empty() {
        out.push('\n');
    }
    for (tag, v) in &cldr {
        out.push_str(&format!("#!cldr {tag} {v}\n"));
    }
    let mut abbreviations = rules.abbreviations().to_vec();
    abbreviations.sort_by(|a, b| a.to_lowercase().cmp(&b.to_lowercase()).then(a.cmp(b)));
    abbreviations.dedup();
    for a in &abbreviations {
        out.push_str(a);
        out.push('\n');
    }
    let mut patterns: Vec<&str> = rules.patterns().collect();
    patterns.sort();
    patterns.dedup();
    for p in patterns {
        out.push_str(p);
        out.push('\n');
    }
    Ok(out)
}

/// Split `rest` (after the opening slash) at the closing unescaped
/// slash: the pattern with `\/` unescaped, and what follows.
fn split_pattern(rest: &str) -> Option<(String, &str)> {
    let mut pattern = String::new();
    let mut chars = rest.char_indices();
    while let Some((i, c)) = chars.next() {
        match c {
            '\\' => match chars.next() {
                Some((_, '/')) => pattern.push('/'),
                Some((_, d)) => {
                    pattern.push('\\');
                    pattern.push(d);
                }
                None => return None,
            },
            '/' => return Some((pattern, &rest[i + 1..])),
            _ => pattern.push(c),
        }
    }
    None
}

#[cfg(feature = "uax29")]
impl Syndesmos {
    /// unicode-segmentation's `split_sentence_bound_indices`, bonds
    /// applied: `(byte offset, segment)` per sentence.
    pub fn split_sentence_bound_indices<'a>(&self, text: &'a str) -> Vec<(usize, &'a str)> {
        use unicode_segmentation::UnicodeSegmentation;
        let raw: Vec<usize> = text
            .split_sentence_bound_indices()
            .map(|(at, _)| at)
            .filter(|&at| at > 0)
            .collect();
        let kept = self.apply(text, &raw);
        let mut out = Vec::with_capacity(kept.len() + 1);
        let mut start = 0;
        for b in kept {
            out.push((start, &text[start..b]));
            start = b;
        }
        if start < text.len() || out.is_empty() && !text.is_empty() {
            out.push((start, &text[start..]));
        }
        out
    }

    /// unicode-segmentation's `unicode_sentences`, bonds applied.
    pub fn unicode_sentences<'a>(&self, text: &'a str) -> Vec<&'a str> {
        self.split_sentence_bound_indices(text)
            .into_iter()
            .map(|(_, s)| s)
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_the_three_kinds() {
        let s = Syndesmos::parse("# c\nDr.\n\nMrs.  # honorific\n/[A-Z]\\. [A-Z]/\n/etc\\. [a-z]/i  # comment\n/a\\/b/\n").unwrap();
        assert_eq!(s.abbreviations(), ["Dr.", "Mrs."]);
        let p: Vec<&str> = s.patterns().collect();
        assert_eq!(p, ["/[A-Z]\\. [A-Z]/", "/etc\\. [a-z]/i", "/a/b/"]);
        assert!(Syndesmos::parse("/unclosed").is_err());
        assert!(Syndesmos::parse("/x/ junk").is_err());
        assert!(Syndesmos::parse("/(/").is_err());
        assert!(
            Syndesmos::parse("#!include en.desm").is_err(),
            "no base to resolve against"
        );
        assert!(Syndesmos::parse("#!frobnicate").is_err());
    }

    #[test]
    fn canon_is_stable_and_explicit() {
        let dir = std::env::temp_dir().join(format!("syndesmos-canon-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("house.desm"), "# house\nSt.\n/x [a-z]/\n").unwrap();
        let a = "# top comment\n# second line\n\n#!cldr en\nMrs.  # honorific\n# between\nDr.\n#!include house.desm\n/b [a-z]/i\nDr.\n/a [a-z]/\n";
        let c = canon(a, Some(&dir)).unwrap();
        assert_eq!(
            c,
            format!(
                "# top comment\n# second line\n#!cldr en {CLDR_VERSION}\nDr.\nMrs.\nSt.\n/a [a-z]/\n/b [a-z]/i\n/x [a-z]/\n"
            )
        );
        // Order and comments do not change the canonical form.
        let b = "# top comment\n# second line\n/a [a-z]/\n#!include house.desm\nDr.\n#!cldr en 48.2\n/b [a-z]/i\nMrs.\n";
        assert_eq!(canon(b, Some(&dir)).unwrap(), c);
        // No head comment, no directives: rules only.
        assert_eq!(canon("Z.\nA.\n", None).unwrap(), "A.\nZ.\n");
        assert!(canon("#!cldr en 1.0\n", None).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn include_resolves_against_the_file() {
        let dir = std::env::temp_dir().join(format!("syndesmos-include-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("sub")).unwrap();
        std::fs::write(dir.join("base.desm"), "Dr.\n/[?!]” [a-z]/\n").unwrap();
        std::fs::write(
            dir.join("sub").join("mine.desm"),
            "#!include ../base.desm\nMrs.\n",
        )
        .unwrap();
        let s = Syndesmos::load(dir.join("sub").join("mine.desm")).unwrap();
        assert_eq!(s.abbreviations(), ["Dr.", "Mrs."]);
        assert_eq!(s.patterns().count(), 1);
        // A cycle is an error naming the file; a missing include too.
        std::fs::write(dir.join("a.desm"), "#!include b.desm\n").unwrap();
        std::fs::write(dir.join("b.desm"), "#!include a.desm\n").unwrap();
        let err = Syndesmos::load(dir.join("a.desm")).unwrap_err().to_string();
        assert!(err.contains("cycle"), "{err}");
        assert!(Syndesmos::load(dir.join("sub").join("none.desm")).is_err());
        std::fs::write(dir.join("c.desm"), "#!include nowhere.desm\n").unwrap();
        assert!(
            Syndesmos::load(dir.join("c.desm"))
                .unwrap_err()
                .to_string()
                .contains("nowhere.desm")
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn bonds_straddle_the_boundary() {
        let s = Syndesmos::parse("Dr.\n/[A-Z]\\. [A-Z]/\n/[?!]” [a-z]/\n").unwrap();
        let t = "I met Dr. Smith. J. R. R. wrote. “Why?” he asked. Undr. Then.";
        let at = |w: &str| t.find(w).unwrap();
        assert!(s.bonds(t, at("Smith")));
        assert!(s.bonds(t, at("R. R.")));
        assert!(s.bonds(t, at("he asked")));
        assert!(!s.bonds(t, at("J. R.")));
        assert!(!s.bonds(t, at("Then")), "Undr. is not Dr.");
        assert!(!s.bonds(t, 0));
    }

    #[test]
    fn overlapping_matches_straddle_every_break() {
        // `J. R` and `R. R` overlap; a non-overlapping scan finds
        // only the first and misses the second break.
        let s = Syndesmos::parse("/[A-Z]\\. [A-Z]/\n").unwrap();
        let t = "J. R. R. Tolkien wrote. So did others.";
        let at = |w: &str| t.find(w).unwrap();
        assert!(s.bonds(t, at("R. R.")));
        assert!(s.bonds(t, at("R. Tolkien")));
        assert!(s.bonds(t, at("Tolkien")));
        assert!(!s.bonds(t, at("So did")));
        assert_eq!(
            s.apply(
                t,
                &[at("R. R."), at("R. Tolkien"), at("Tolkien"), at("So did")]
            ),
            [at("So did")]
        );
    }

    #[cfg(feature = "uax29")]
    #[test]
    fn drop_in_joins_sentences() {
        let s = Syndesmos::parse("Dr.\n").unwrap();
        let t = "I met Dr. Smith. He left.";
        assert_eq!(s.unicode_sentences(t), ["I met Dr. Smith. ", "He left."]);
        assert_eq!(
            Syndesmos::empty().unicode_sentences(t),
            ["I met Dr. ", "Smith. ", "He left."]
        );
        assert_eq!(s.split_sentence_bound_indices(t)[1].0, 17);
        assert!(Syndesmos::empty().unicode_sentences("").is_empty());
    }

    #[test]
    fn the_cldr_lists_load_and_bond() {
        for tag in Syndesmos::cldr_languages() {
            assert!(!Syndesmos::cldr(tag).unwrap().is_empty(), "{tag}");
        }
        let en = Syndesmos::cldr("en").unwrap();
        assert!(en.bonds("See Mr. Twain.", 8));
        let de = Syndesmos::cldr("de").unwrap();
        assert!(de.bonds("Er kam z.B. heute.", 12));
        // The directive: shipped release, matching pin, other pin.
        assert_eq!(
            Syndesmos::parse("#!cldr en").unwrap().abbreviations().len(),
            en.abbreviations().len()
        );
        assert!(
            !Syndesmos::parse(&format!("#!cldr en {CLDR_VERSION}\nDr.\n"))
                .unwrap()
                .is_empty()
        );
        let err = Syndesmos::parse("#!cldr en 1.0").unwrap_err().to_string();
        assert!(err.contains("desm cldr get 1.0"), "{err}");
        assert!(
            Syndesmos::parse("#!cldr xx")
                .unwrap_err()
                .to_string()
                .contains("no CLDR list")
        );
        assert!(Syndesmos::parse("#!cldr en 48.2 extra").is_err());
    }
}
